import {
  Activity,
  ArrowLeftRight,
  BadgeDollarSign,
  BarChart3,
  BatteryCharging,
  Box,
  BrickWall,
  Calculator,
  Clock3,
  Cuboid,
  Gauge,
  Grid3X3,
  LayoutGrid,
  Minus,
  PaintBucket,
  PaintRoller,
  Percent,
  PieChart,
  Plus,
  Receipt,
  Ruler,
  Scale,
  Sigma,
  Square,
  Timer,
  TrendingUp,
  WalletCards,
  Waves,
  Zap,
  Droplets,
  Thermometer,
  Cpu,
  Network,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { CalculatorIconKey } from '../types/iconKeys';

export const calculatorIconMap: Record<CalculatorIconKey, LucideIcon> = {
  'rule-of-three': Scale,
  percentage: Percent,
  increase: Plus,
  discount: Minus,
  area: Square,
  volume: Box,
  'unit-cost': Calculator,
  current: Activity,
  power: Gauge,
  voltage: BatteryCharging,
  'ohms-law': Sigma,
  resistors: Network,
  consumption: BarChart3,
  'apparent-power': Zap,
  lighting: Zap,
  reservoir: Droplets,
  'daily-consumption': Droplets,
  autonomy: Clock3,
  flow: Waves,
  'fill-time': Timer,
  pressure: Gauge,
  'paint-area': PaintRoller,
  'paint-liters': PaintBucket,
  'paint-budget': Receipt,
  'wall-area': Ruler,
  'floor-area': Grid3X3,
  'concrete-volume': Cuboid,
  blocks: BrickWall,
  tiles: LayoutGrid,
  labor: WalletCards,
  'final-price': BadgeDollarSign,
  daily: Clock3,
  hourly: Timer,
  installments: PieChart,
  upfront: TrendingUp,
  'volume-converter': ArrowLeftRight,
  'pressure-converter': Gauge,
  'power-converter': Cpu,
  'thermal-converter': Thermometer,
};
