import {
  ArrowLeftRight,
  BadgeDollarSign,
  Building2,
  Calculator,
  ClipboardList,
  Droplets,
  FileBarChart2,
  Home,
  Lightbulb,
  Paintbrush,
  Settings,
  ShoppingBag,
  Snowflake,
  Store,
  Sun,
  Wrench,
  Zap,
  Cpu,
  CircuitBoard,
  Factory,
  RotateCcw,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { ModuleIconKey } from '../types/iconKeys';

export const moduleIconMap: Record<ModuleIconKey, LucideIcon> = {
  home: Home,
  calculations: Calculator,
  survey: ClipboardList,
  budgets: BadgeDollarSign,
  reports: FileBarChart2,
  'clients-os': ClipboardList,
  settings: Settings,
  store: Store,
  'fundamentals-general': Calculator,
  'fundamentals-electrical': Zap,
  'electrical-installations': Wrench,
  lighting: Lightbulb,
  hydraulics: Droplets,
  painting: Paintbrush,
  construction: Building2,
  refrigeration: Snowflake,
  'automation-industrial': Factory,
  electronics: CircuitBoard,
  motors: RotateCcw,
  transformers: Cpu,
  solar: Sun,
  'technical-budget': ShoppingBag,
  converters: ArrowLeftRight,
};
